name: Make-Curl-Android

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
       ndk-version: r21e
       add-to-path: false
       
    - name: Checking Files
      run: |
        tree .
       
    - name: Building
      run: |
        cd curl-compile-scripts
        export NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}
        chmod +x ./build_Android.sh
        ./build_Android.sh
